ALTER TABLE public.user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.regions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_explanations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ml_model_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_secrets DISABLE ROW LEVEL SECURITY;
